Repository planetarium/NineChronicles.Mods, pull requests merged in 2024-03, with the labels that each got.

#2 Create BEPINEX_TUTORIAL.md
  BEPINEX_TUTORIAL.md
Labels: Medium

#1 feat: Introduce NineChronicles.Mods solution and PVEHelper project
  .gitignore
  NineChronicles.Mods.PVEHelper/BlockSimulation/ActionContext.cs
  NineChronicles.Mods.PVEHelper/BlockSimulation/Actions/HackAndSlashSimulation.cs
  NineChronicles.Mods.PVEHelper/BlockSimulation/MackStateConverters.cs
  NineChronicles.Mods.PVEHelper/BlockSimulation/MockAccountState.cs
  NineChronicles.Mods.PVEHelper/BlockSimulation/MockWorldState.cs
  NineChronicles.Mods.PVEHelper/BlockSimulation/RandomImpl.cs
  NineChronicles.Mods.PVEHelper/BlockSimulation/WorldFactory.cs
  NineChronicles.Mods.PVEHelper/GUI/IGUI.cs
  NineChronicles.Mods.PVEHelper/GUI/WinRateGUI.cs
  NineChronicles.Mods.PVEHelper/NineChronicles.Mods.PVEHelper.csproj
  NineChronicles.Mods.PVEHelper/PVEHelperPlugin.cs
  NineChronicles.Mods.PVEHelper/Patches/BattlePreparationWidgetPatch.cs
  NineChronicles.Mods.sln
Labels: Extra Large

#4 Add util scripts
  .gitignore
  NineChronicles.Mods.PVEHelper/NineChronicles.Mods.PVEHelper.csproj
  scripts/create-dotent.ps1
  scripts/inject-plugins.ps1
Labels: Large

#5 Adjust GUI.matrix to re-scale IMGUI stuffs.
  NineChronicles.Mods.PVEHelper/GUIs/GUIToolbox.cs
  NineChronicles.Mods.PVEHelper/GUIs/IGUI.cs
  NineChronicles.Mods.PVEHelper/GUIs/WinRateGUI.cs
  NineChronicles.Mods.PVEHelper/PVEHelperPlugin.cs
Labels: Extra Small

#9 Remove unity engine envs
  NineChronicles.Mods.PVEHelper/NineChronicles.Mods.PVEHelper.csproj
  scripts/create-dotent.ps1
Labels: Small

#10 Add csv utils
  NineChronicles.Mods.PVEHelper/Models/EquipmentCache.cs
  NineChronicles.Mods.PVEHelper/NineChronicles.Mods.PVEHelper.csproj
  NineChronicles.Mods.PVEHelper/Utils/CsvParser.cs
  NineChronicles.Mods.PVEHelper/Utils/CsvUtil.cs
Labels: Small

#6 Introduce `InventoryGUI`
  NineChronicles.Mods.PVEHelper/Extensions/ItemExtensions.cs
  NineChronicles.Mods.PVEHelper/Extensions/SpriteExtensions.cs
  NineChronicles.Mods.PVEHelper/GUIs/InventoryGUI.cs
  NineChronicles.Mods.PVEHelper/PVEHelperPlugin.cs
  NineChronicles.Mods.PVEHelper/Pools/ItemTexturePool.cs
  NineChronicles.Mods.PVEHelper/ViewModels/InventoryViewModel.cs
Labels: Large

#12 Refactor log method
  NineChronicles.Mods.PVEHelper/GUIs/GUIToolbox.cs
  NineChronicles.Mods.PVEHelper/GUIs/InventoryGUI.cs
  NineChronicles.Mods.PVEHelper/GUIs/WinRateGUI.cs
  NineChronicles.Mods.PVEHelper/PVEHelperPlugin.cs
  NineChronicles.Mods.PVEHelper/Patches/BattlePreparationWidgetPatch.cs
Labels: Extra Small

#7 Implement stage simulation mode
  NineChronicles.Mods.PVEHelper/GUIs/OverlayGUI.cs
  NineChronicles.Mods.PVEHelper/GUIs/StageSimulateGUI.cs
  NineChronicles.Mods.PVEHelper/PVEHelperPlugin.cs
Labels: Large

#17 Change winrate -> wave clear count
  NineChronicles.Mods.PVEHelper/BlockSimulation/Actions/HackAndSlashSimulation.cs
  NineChronicles.Mods.PVEHelper/GUIs/OverlayGUI.cs
  NineChronicles.Mods.PVEHelper/GUIs/StageSimulateGUI.cs
  NineChronicles.Mods.PVEHelper/GUIs/WinRateGUI.cs
  NineChronicles.Mods.PVEHelper/PVEHelperPlugin.cs
Labels: Medium

#18 Add ModItemFactory
  NineChronicles.Mods.PVEHelper/BlockSimulation/ModItemFactory.cs
Labels: Small

#19 equip gui
  NineChronicles.Mods.PVEHelper/BlockSimulation/Actions/HackAndSlashSimulation.cs
  NineChronicles.Mods.PVEHelper/GUIs/EquipGUI.cs
  NineChronicles.Mods.PVEHelper/GUIs/StageSimulateGUI.cs
  NineChronicles.Mods.PVEHelper/Manger/ModInventoryManager.cs
  NineChronicles.Mods.PVEHelper/PVEHelperPlugin.cs
Labels: Medium

#20 fix: CsvParser
  NineChronicles.Mods.PVEHelper/BlockSimulation/ModItemFactory.cs
  NineChronicles.Mods.PVEHelper/Utils/CsvParser.cs
Labels: Extra Small

#22 improve `ItemCreationGUI`
  NineChronicles.Mods.PVEHelper/GUIs/ItemRecipesGUI.cs
  NineChronicles.Mods.PVEHelper/GUIs/UseItemRecipeGUI.cs
  NineChronicles.Mods.PVEHelper/PVEHelperPlugin.cs
  NineChronicles.Mods.PVEHelper/ViewModels/UseItemRecipeViewModel.cs
Labels: Small

#24 Correct camera recover logic
  NineChronicles.Mods.PVEHelper/PVEHelperPlugin.cs
Labels: bug, Extra Small

#25 draw tooltip of inventory slot
  NineChronicles.Mods.PVEHelper/GUIs/GUIToolbox.cs
  NineChronicles.Mods.PVEHelper/GUIs/InventoryGUI.cs
  NineChronicles.Mods.PVEHelper/GUIs/ItemRecipesGUI.cs
  NineChronicles.Mods.PVEHelper/ViewModels/InventoryViewModel.cs
  NineChronicles.Mods.PVEHelper/ViewModels/ItemRecipesViewModel.cs
Labels: Small

#26 track daily open event of Athena mod
  NineChronicles.Mods.PVEHelper/PVEHelperPlugin.cs
Labels: Extra Small

#27 add Aura tab to Inventory
  NineChronicles.Mods.PVEHelper/GUIs/InventoryGUI.cs
  NineChronicles.Mods.PVEHelper/ViewModels/InventoryViewModel.cs
Labels: Extra Small

#28 Open all mod GUIs in TabGUI
  NineChronicles.Mods.PVEHelper/GUIs/OverlayGUI.cs
  NineChronicles.Mods.PVEHelper/GUIs/StageSimulateGUI.cs
  NineChronicles.Mods.PVEHelper/GUIs/TabGUI.cs
  NineChronicles.Mods.PVEHelper/PVEHelperPlugin.cs
Labels: Large

#30 Prevent to add item twice
  NineChronicles.Mods.PVEHelper/BlockSimulation/Actions/HackAndSlashSimulation.cs
Labels: bug

#31 improve inventory tooltip style
  NineChronicles.Mods.PVEHelper/GUIs/InventoryGUI.cs
  NineChronicles.Mods.PVEHelper/PVEHelperPlugin.cs
  NineChronicles.Mods.PVEHelper/Pools/ColorTexturePool.cs
Labels: Extra Small

#33 Avoid to hide item name
  NineChronicles.Mods.PVEHelper/GUIs/InventoryGUI.cs
  NineChronicles.Mods.PVEHelper/GUIs/ItemRecipesGUI.cs
Labels: Extra Small

#34 Avoid to hide item description
  NineChronicles.Mods.PVEHelper/GUIs/InventoryGUI.cs
Labels: Extra Small

#35 add aura tab to `ItemRecipesGUI`
  NineChronicles.Mods.PVEHelper/GUIs/InventoryGUI.cs
  NineChronicles.Mods.PVEHelper/GUIs/ItemRecipesGUI.cs
  NineChronicles.Mods.PVEHelper/ViewModels/InventoryViewModel.cs
  NineChronicles.Mods.PVEHelper/ViewModels/ItemRecipesViewModel.cs
Labels: Extra Small

#36 Notify item creation
  NineChronicles.Mods.PVEHelper/GUIs/InventoryGUI.cs
  NineChronicles.Mods.PVEHelper/GUIs/ItemCreationGUI.cs
  NineChronicles.Mods.PVEHelper/GUIs/NotificationGUI.cs
  NineChronicles.Mods.PVEHelper/GUIs/UseItemRecipeGUI.cs
  NineChronicles.Mods.PVEHelper/PVEHelperPlugin.cs
  NineChronicles.Mods.PVEHelper/Pools/ColorTexturePool.cs
Labels: Small

#38 Improve simulation GUI
  NineChronicles.Mods.PVEHelper/GUIs/StageSimulateGUI.cs
Labels: Extra Small

#39 expand tabs
  NineChronicles.Mods.PVEHelper/GUIs/InventoryGUI.cs
  NineChronicles.Mods.PVEHelper/GUIs/ItemCreationGUI.cs
  NineChronicles.Mods.PVEHelper/GUIs/ItemRecipesGUI.cs
  NineChronicles.Mods.PVEHelper/Manger/ModInventoryManager.cs
  NineChronicles.Mods.PVEHelper/PVEHelperPlugin.cs
  NineChronicles.Mods.PVEHelper/ViewModels/InventoryViewModel.cs
Labels: Small

#41 fix inventory position
  NineChronicles.Mods.PVEHelper/GUIs/ItemCreationGUI.cs
  NineChronicles.Mods.PVEHelper/PVEHelperPlugin.cs
Labels: Extra Small

#42 identify inventory item and more
  NineChronicles.Mods.PVEHelper/BlockSimulation/ModItemFactory.cs
  NineChronicles.Mods.PVEHelper/GUIs/EnhancementGUI.cs
  NineChronicles.Mods.PVEHelper/GUIs/InventoryGUI.cs
  NineChronicles.Mods.PVEHelper/GUIs/StageSimulateGUI.cs
  NineChronicles.Mods.PVEHelper/PVEHelperPlugin.cs
  NineChronicles.Mods.PVEHelper/Pools/ColorTexturePool.cs
  NineChronicles.Mods.PVEHelper/ViewModels/InventoryViewModel.cs
Labels: Extra Large
