Repository planetarium/NineChronicles.Mods, pull requests merged in 2024-04, with the labels that each got.

#45 fix: item creation bug
  NineChronicles.Mods.Athena/AthenaPlugin.cs
  NineChronicles.Mods.Athena/BlockSimulation/RandomFakeImpl.cs
  NineChronicles.Mods.Athena/Factories/ModItemFactory.cs
  NineChronicles.Mods.Athena/GUIs/EnhancementGUI.cs
  NineChronicles.Mods.Athena/GUIs/UseItemRecipeGUI.cs
  NineChronicles.Mods.Athena/Models/ModItem.cs
Labels: Small

#47 implement `AdHoc.BurnAsset` plugin
  AdHoc.BurnAsset/AdHoc.BurnAsset.csproj
  AdHoc.BurnAsset/BurnAssetPlugin.cs
  AdHoc.BurnAsset/GUIToolbox.cs
  NineChronicles.Mods.sln
Labels: Large

#48 track installation
  NineChronicles.Mods.Athena/AthenaPlugin.cs
Labels: Extra Small

#51 to string with invariant culture info
  NineChronicles.Mods.Athena/Utils/CsvUtil.cs
Labels: bug, Extra Small

#52 chore: chore
  NineChronicles.Mods.Athena/AthenaPlugin.cs
  NineChronicles.Mods.Athena/GUIs/InventoryGUI.cs
  NineChronicles.Mods.Athena/Pools/ColorTexturePool.cs
  NineChronicles.Mods.Athena/ViewModels/InventoryViewModel.cs
Labels: Extra Small

#55 Add scripts for macos
  scripts/inject-plugins.sh
  scripts/run-9c-with-mods.sh
Labels: Small

#57 fix tab name text of inventory
  NineChronicles.Mods.Athena/GUIs/InventoryGUI.cs
  NineChronicles.Mods.Athena/GUIs/ItemRecipesGUI.cs
  NineChronicles.Mods.Athena/ViewModels/InventoryViewModel.cs
  NineChronicles.Mods.Athena/ViewModels/ItemRecipesViewModel.cs
Labels: Extra Small

#58 fix and ontimize `HackAndSlashSimulator`
  NineChronicles.Mods.Athena/GUIs/StageSimulateGUI.cs
  NineChronicles.Modules.BlockSimulation/ActionSimulators/HackAndSlashSimulator.cs
Labels: Medium

#59 fix bug
  NineChronicles.Modules.BlockSimulation/ActionSimulators/HackAndSlashSimulator.cs
Labels: bug, Extra Small
